### ISSUE TITLE
Border incomplete without mounts

### ISSUE THREAD

**Issue by Matir** [twitchyliquid64/kcgen#1]
If you use kc-outline to generate an outline with a border, but without mounts, the corners are not included in the resulting design.
![border_fail](https://user-images.githubusercontent.com/808960/44633204-9eabef00-a93c-11e8-826d-490417b14e86.png)

**Comment by Matir** [comment]
I should say "the corners are not included in the resulting outline design"

**Comment by twitchyliquid64** [comment]
Closing as obsoleted by new version.
